-- RedLink initial schema: 7 tables.
-- Never edit this file after it has run anywhere; add V2__... for changes.

-- ---------------------------------------------------------------------------
-- hospitals (approved_by -> users is added after users exists)
-- ---------------------------------------------------------------------------
CREATE TABLE hospitals (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR(200) NOT NULL,
    registration_no  VARCHAR(100) NOT NULL,
    address          VARCHAR(300) NOT NULL,
    city             VARCHAR(100) NOT NULL,
    phone            VARCHAR(30)  NOT NULL,
    status           VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    approved_by      BIGINT,
    approved_at      TIMESTAMPTZ,
    rejection_reason VARCHAR(500),
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT uq_hospitals_registration_no UNIQUE (registration_no),
    CONSTRAINT ck_hospitals_status CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
    CONSTRAINT ck_hospitals_rejection_reason CHECK (status = 'REJECTED' OR rejection_reason IS NULL)
);

-- ---------------------------------------------------------------------------
-- users
-- ---------------------------------------------------------------------------
CREATE TABLE users (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email                VARCHAR(255) NOT NULL,
    password_hash        VARCHAR(100) NOT NULL,
    full_name            VARCHAR(150) NOT NULL,
    phone                VARCHAR(30),
    role                 VARCHAR(20)  NOT NULL,
    hospital_id          BIGINT REFERENCES hospitals (id),
    enabled              BOOLEAN      NOT NULL DEFAULT TRUE,
    must_change_password BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT ck_users_role CHECK (role IN ('ADMIN', 'HOSPITAL_STAFF', 'DONOR')),
    -- hospital staff must belong to a hospital; nobody else may
    CONSTRAINT ck_users_hospital CHECK ((role = 'HOSPITAL_STAFF') = (hospital_id IS NOT NULL))
);

-- hospitals and users reference each other, so this key is added last
ALTER TABLE hospitals
    ADD CONSTRAINT fk_hospitals_approved_by FOREIGN KEY (approved_by) REFERENCES users (id);

-- ---------------------------------------------------------------------------
-- donors (one profile per user)
-- ---------------------------------------------------------------------------
CREATE TABLE donors (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            BIGINT      NOT NULL REFERENCES users (id),
    blood_group        VARCHAR(3)  NOT NULL,
    date_of_birth      DATE        NOT NULL,
    city               VARCHAR(100) NOT NULL,
    available          BOOLEAN     NOT NULL DEFAULT TRUE,
    last_donation_date DATE,

    CONSTRAINT uq_donors_user_id UNIQUE (user_id),
    CONSTRAINT ck_donors_blood_group CHECK (blood_group IN ('A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'))
);

-- speeds up the matching query
CREATE INDEX idx_donors_matching ON donors (blood_group, available, city);

-- ---------------------------------------------------------------------------
-- blood_requests
-- ---------------------------------------------------------------------------
CREATE TABLE blood_requests (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hospital_id  BIGINT       NOT NULL REFERENCES hospitals (id),
    created_by   BIGINT       NOT NULL REFERENCES users (id),
    blood_group  VARCHAR(3)   NOT NULL,
    units_needed INTEGER      NOT NULL,
    urgency      VARCHAR(10)  NOT NULL,
    city         VARCHAR(100) NOT NULL,
    status       VARCHAR(20)  NOT NULL DEFAULT 'OPEN',
    needed_by    TIMESTAMPTZ  NOT NULL,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    closed_at    TIMESTAMPTZ,

    CONSTRAINT ck_requests_units CHECK (units_needed > 0),
    CONSTRAINT ck_requests_blood_group CHECK (blood_group IN ('A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-')),
    CONSTRAINT ck_requests_urgency CHECK (urgency IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    CONSTRAINT ck_requests_status CHECK (status IN ('OPEN', 'FULFILLED', 'CANCELLED', 'EXPIRED')),
    -- closed_at is set exactly when the request stops being OPEN
    CONSTRAINT ck_requests_closed_at CHECK ((status = 'OPEN') = (closed_at IS NULL))
);

CREATE INDEX idx_requests_status_city ON blood_requests (status, city);
CREATE INDEX idx_requests_hospital ON blood_requests (hospital_id);

-- ---------------------------------------------------------------------------
-- donor_responses (one per donor per request; withdrawing updates the row)
-- ---------------------------------------------------------------------------
CREATE TABLE donor_responses (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id   BIGINT      NOT NULL REFERENCES blood_requests (id),
    donor_id     BIGINT      NOT NULL REFERENCES donors (id),
    status       VARCHAR(20) NOT NULL,
    responded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT uq_responses_request_donor UNIQUE (request_id, donor_id),
    CONSTRAINT ck_responses_status CHECK (status IN ('ACCEPTED', 'DECLINED', 'WITHDRAWN'))
);

-- request_id lookups use the unique index above; this covers donor_id lookups
CREATE INDEX idx_responses_donor ON donor_responses (donor_id);

-- ---------------------------------------------------------------------------
-- donations
-- ---------------------------------------------------------------------------
CREATE TABLE donations (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    donor_id      BIGINT  NOT NULL REFERENCES donors (id),
    hospital_id   BIGINT  NOT NULL REFERENCES hospitals (id),
    request_id    BIGINT  REFERENCES blood_requests (id),
    donation_date DATE    NOT NULL,
    units         INTEGER NOT NULL DEFAULT 1,

    CONSTRAINT ck_donations_units CHECK (units > 0)
);

CREATE INDEX idx_donations_donor ON donations (donor_id);

-- ---------------------------------------------------------------------------
-- notifications
-- ---------------------------------------------------------------------------
CREATE TABLE notifications (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL REFERENCES users (id),
    request_id BIGINT       REFERENCES blood_requests (id),
    message    VARCHAR(500) NOT NULL,
    is_read    BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- unread notifications for a user, newest first
CREATE INDEX idx_notifications_user_unread ON notifications (user_id, is_read, created_at DESC);
