spring.application.name=backend
server.port=8080

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/redLink
spring.datasource.username=postgres
# Password is in application-local.properties (git-ignored)
spring.config.import=optional:classpath:application-local.properties

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ddl-auto=update makes Hibernate create and update tables 
#from your Java classes automatically, which is fine while you're developing.