// Suggestions for city fields: Sri Lanka's 25 district capitals. Matching compares cities by name,
// so suggesting one spelling ("Nuwara Eliya", not "N'Eliya") keeps donors and requests comparable.
// People can still type a city that isn't listed.
export const CITIES = [
  'Ampara',
  'Anuradhapura',
  'Badulla',
  'Batticaloa',
  'Colombo',
  'Galle',
  'Gampaha',
  'Hambantota',
  'Jaffna',
  'Kalutara',
  'Kandy',
  'Kegalle',
  'Kilinochchi',
  'Kurunegala',
  'Mannar',
  'Matale',
  'Matara',
  'Monaragala',
  'Mullaitivu',
  'Nuwara Eliya',
  'Polonnaruwa',
  'Puttalam',
  'Ratnapura',
  'Trincomalee',
  'Vavuniya',
] as const;
